version: '3'
services:
 da1:
  image: tornode:latest
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    default:
      ipv4_address: 172.20.0.3

 da2:
  image: tornode:latest
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    default:
      ipv4_address: 172.20.0.2


 da3:
  image: tornode:latest
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    default:
      ipv4_address: 172.20.0.4


 relay:
  image: tornode:latest
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
 exit:
  image: tornode:latest
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
 client:
  image: tornode:latest
  #ports:
    # Setups a listener on host machine
    # - "9050:9050"
    # - "9051:9051"
    # - "9500:9500"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da1
    - da2
    - da3
 #networks:
   #default:
   # ipv4_address: 172.20.0.14
 hs:
  image: tornode:latest
  #expose:
  #  - "80"
  environment:
    ROLE: HS
    # This will create a hidden service that points to
    # the service "web" which is runing nginx. You can 
    # change this to whatever ip or hostname you want
    TOR_HS_PORT: "23"
    TOR_HS_ADDR: "172.20.0.15"
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  links:
    - mirai_cnc
      # web:
      #  image: nginx
 mirai_cnc:
  image: cnc
  expose:
    - "23"
  networks:
    default:
      ipv4_address: 172.20.0.15
 mirai_bot:
  image: bot
  environment:
    PROXY: 172.20.0.14
  volumes:
    - ./tor:/tor
  depends_on:
    - hs
    - mirai_cnc
  #expose:
  #  - "80"
  
networks:
 default:
  driver: bridge
  ipam:
    driver: default
    config:
      - subnet: 172.20.0.0/16
